### ISSUE TITLE
New Logo/icon Design

### ISSUE THREAD

**Issue by zularizal** [AYIDouble/Binary-Calculator-Android-Java-App#3]
Hi @AYIDouble ,  I'm a graphic designer, after I review your project, I'm interested in your project. The previous logo looks less modern. I want to create a new, modern and elegant logo for your project. And it's free. How do you think?

**Comment by AYIDouble** [comment]
I would find it great. 
I would use the logo for both of my apps, the binary and trinary calculator, 
just one of the both logos should be darker. 
Many Thanks 😃👍

**Comment by zularizal** [comment]
Okay. Give me time to make it. I will upload the logo proposal in the next reply.

**Comment by zularizal** [comment]
Sorry for a long time, this is my design logo for your projects. In the binary logo I added binary numbers to the center, while on the binary I added trinary numbers to the center.

What do you think? if something wants to be changed please let me know.
![bitmap](https://user-images.githubusercontent.com/38547278/47401595-34f96700-d76c-11e8-9f1f-6adc1fdf026e.png)

**Comment by AYIDouble** [comment]
I like it, it looks awesome.  😃👍
But would it be possible to use - 0 + instead of 0011 in the trinary logo? (- 0 + symbolises balanced Ternary)
After that, you can fork the projects and add the Logos into the Images folder (https://github.com/AYIDouble/Binary-Calculator-Android-Java-App/tree/master/Images), (https://github.com/AYIDouble/Trinary-Calculator-Android-Java-App/tree/master/Images) and open a Pull Request.
Many Thanks 😃👍

**Comment by zularizal** [comment]
Sorry late @AYIDouble , is this what you mean?

![tes](https://user-images.githubusercontent.com/38547278/48041978-2d957d00-e1b2-11e8-8f94-992a7509cf22.png)

**Comment by AYIDouble** [comment]
Yes, this is exactly what I meant.
Feel free to open the pull requests.
Many Thanks 😃👍

**Comment by zularizal** [comment]
Hi @AYIDouble , I have added a new icon and logo to your project.
You can use the icon in the app launcher icon or playstore.
You can use the logo on the web. Like favicon, header, and others.

And also I have uploaded these logos to the drive.
https://drive.google.com/open?id=1kPcSHgatKv1ZRA9q0mFl5dtOZFM2uSgj
